# Chat Screen
<MetroChat>:
    name : "chathub"

    #Chat Background
    FloatLayout:
        canvas.before:
            Color:
                rgba: 0.75, 0.75, 0.75, 1
            Rectangle:
                pos: self.pos
                size: self.size[0] / 2.5, self.size[1]
            Color:
                rgba: 0.5, 0.5, 0.5, 1
            Rectangle:
                pos: self.pos[0] + self.size[0] / 2.5 , self.pos[1]
                size: 100,100
